version: "3.8"

services:
  kafka:
    # image: "docker.io/bitnami/kafka:3.4.0"
    image: "docker-hub.repo01.vkbads.de/bitnami/kafka:3.4.0"
    ports:
      - "9092:9092"
      - "9093:9093" # evtl hier 92->93 und dann external advertive auch auf port 92?
    volumes:
      - "./v_kafka_data:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    healthcheck:
      test: kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
  akhq:
    # image: "docker.io/tchiotludo/akhq:dev" # soablds ein neues reelease gibt, des nutzen
    image: "docker-hub.repo01.vkbads.de/tchiotludo/akhq:dev" # soablds ein neues reelease gibt, des nutzen
    ports:
      - "9080:8080"
    volumes:
      - "./v_akhq/application.yml:/app/application.yml:ro"
